# Imposta la lunghezza massima della riga a 88 caratteri
line-length = 88

# Seleziona le regole da applicare.
# 'E' = pycodestyle (errori di stile)
# 'F' = pyflakes (errori di logica come import non usati)
select = ["E", "F"]

# Ignora l'errore E203, che è incompatibile con black/ruff
ignore = ["E203"]

[lint]
# Abilita la correzione automatica per gli import non usati
unfixable = []

[format]
# Abilita il formattatore (alternativa a black)
# Non serve configurazione extra, usa lo standard di 88 caratteri